title: From Zach Import Random
description: > # this means to ignore newlines until "baseurl:"
  This shit does not need a description right now.
permalink: ':title/'
baseurl: "/flexible-jekyll/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Zachary Andrews # add your name
author-img: cowboys.jpg # add your photo
about-author: I'm the best. # add description
twitter: zach_sparrow # add your Twitter handle
facebook: # add your Facebook handle
github: andrewszw # add your Github handle
linkedin: # add your Linkedin handle
email: zacharyandrews93@gmail.com# add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
